version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - josephworks
  ignore:
  - dependency-name: hyperapp
    versions:
    - 2.0.16
